### ISSUE TITLE
post_input! wrong number of type arguments: expected 1, found 2

### ISSUE THREAD

**Issue by lolgesten** [tomaka/rouille#156] opened 2017-11-06 13:42 UTC
It's very possible I'm doing something wrong here.

I believe I'm following the docs/example code, but still I get something strange in the macro.

```
error[E0244]: wrong number of type arguments: expected 1, found 2
   --> src/main.rs:142:33
    |
142 |                       let input = post_input!(&request, {
    |  _________________________________^
143 | |                         descriptor: String
144 | |                     });
    | |______________________^ expected 1 type argument
    |
    = note: this error originates in a macro outside of the current crate
```

Should this work?

**Comment by ALSchwalm** [comment] 2018-04-03 20:55
Just as a heads-up, this is caused by a bug in the `post_input` macro causing it to use the `Result` type from the enclosing scope instead of the standard `Result`. It was fixed in #161 so I think this issue can be closed.

**Closed** 2018-04-04 09:13 UTC
Labels: bug
